; ──────────────────────────────────────────────────────────────────────────
; LoRa Finder — PlatformIO Configuration
; Heltec WiFi LoRa 32 V4 (ESP32-S3 + SX1262 + OLED SSD1306)
; ──────────────────────────────────────────────────────────────────────────

[env:heltec_wifi_lora_32_V4]
platform = espressif32
board    = heltec_wifi_lora_32_V4
framework = arduino

monitor_speed = 115200
upload_speed  = 921600
;upload_port   = COM4

lib_deps =
    olikraus/U8g2 @ ^2.35.30                ; OLED SSD1306 (128x64)
    mprograms/QMC5883LCompass @ ^1.2.1      ; Magnetómetro QMC5883L
    mikalhart/TinyGPSPlus @ ^1.0.3          ; Parser NMEA GPS
    jgromes/RadioLib @ ^7.1.2               ; Radio SX1262 (SX127x también)
    adafruit/Adafruit NeoPixel @ ^1.12.3    ; LED RGB WS2812B

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1
    -I src
    ; Descomentar UNA línea para seleccionar el rol del nodo:
    ;-DNODE_ROLE_SENDER
    -DNODE_ROLE_RECEIVER
